name: Bugsy Segal
favicon: null
layout_spectrum: 0.23577
typography_spectrum: 0.23075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#091128'
    - '#a57302'
    - '#555459'
    - '#fec225'
    - '#fffbe0'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
