name: Bugsy Segal
favicon: null
layout_spectrum: 0.020487124100327492
typography_spectrum: 0.09186045662499964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.10709635587409139
  lightness: 0.39319630339741707
  saturation: 0.09468387952074409
  rhythmicContrast: 0.5145823480561376
purpose: []
