name: Bugsy Segal
favicon: null
layout_spectrum: 0.49271
typography_spectrum: 0.23075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5396cd'
    - '#276598'
    - '#f5fdfe'
    - '#00212d'
    - '#adc0d1'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
